console.log('=== DIAGNOSTICO ===');
console.log('houseScene existe:', !!window.__refs.houseScene);
console.log('houseScene hijos:', window.__refs.houseScene?.children?.length);
console.log('houseScene hijos (nombres):', window.__refs.houseScene?.children?.map(c => c.type));
console.log('houseInterior existe:', !!window.__refs.houseInterior);
console.log('houseInterior hijos:', window.__refs.houseInterior?.children?.length);
console.log('houseInterior visible:', window.__refs.houseInterior?.visible);
console.log('houseInterior esta en la escena:', window.__refs.houseScene?.children?.includes(window.__refs.houseInterior));
console.log('houseCamera pos:', window.__refs.houseCamera?.position);
console.log('player pos:', window.__refs.player?.position);
console.log('player esta en houseScene:', window.__refs.houseScene?.children?.includes(window.__refs.player));